services:
  # Redis Stack with RedisJSON support
  studygarden-redis:
    image: redis/redis-stack:7.2.0-v9
    container_name: studygarden-redis
    ports:
      - "${REDIS_PORT}:6379"
      - "8001:8001" # RedisInsight web UI (optional)
    volumes:
      - redis-data:/data
    environment:
      - REDIS_ARGS=--save 20 1 --loglevel warning
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
    networks:
      - studygarden

  # PostgreSQL Database
  studygarden-psql:
    image: postgres:15
    container_name: studygarden-psql
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - studygarden

  # ArangoDB Database
  studygarden-arangodb:
    image: arangodb:3.12
    container_name: studygarden-arangodb
    ports:
      - "${ARANGO_PORT}:8529"
    volumes:
      - arangodb-data:/var/lib/arangodb3
    environment:
      - ARANGO_ROOT_PASSWORD=${ARANGO_ROOT_PASSWORD}
      - ARANGO_DATABASE=${ARANGO_DB_NAME}
      - ARANGO_USER=${ARANGO_USER}
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "arangosh --server.endpoint tcp://127.0.0.1:8529 --server.username ${ARANGO_USER} --server.password $${ARANGO_ROOT_PASSWORD} --javascript.execute-string 'db._version();'",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - studygarden

networks:
  studygarden:
    driver: bridge

volumes:
  redis-data:
    driver: local
  postgres-data:
    driver: local
  arangodb-data:
    driver: local
